### PR TITLE
Feature/#69 adjust price to quantity

### PR DESCRIPTION
**Pull request by Chester193**

### CODE REVIEW

**Comment by cyngiel** [comment]
Failed to compile
./src/components/FormComponent.jsx
Module not found: Can't resolve 'validator' in '...\ZPI_2020_MenInBlack\taxes-app\src\components'

commit "#67 added indication about product quantity in store" works just fine

**Comment by cyngiel** [comment]
> Failed to compile
> ./src/components/FormComponent.jsx
> Module not found: Can't resolve 'validator' in '...\ZPI_2020_MenInBlack\taxes-app\src\components'
> 
> commit "#67 added indication about product quantity in store" works just fine

I am dumb, npm install fixed the problem.
Discovered quantity display bug.

**Comment by pawellazicki** [comment]
stock quantity isn't displayed

**Comment by pawellazicki** [comment]
even if quantity equals 1000, display 10

**Comment by pawellazicki** [comment]
there is no difference between 100 and 10 in adjusted price

**Pull request merged**
